### ISSUE TITLE
No puedo clonar el repositorio....

### ISSUE THREAD

**Issue by abdisoftware** [Android-Avanzado/androidapp#1]
$ git clone https://github.com/Android-Avanzado/androidapp.git
Cloning into 'androidapp'...
remote: Enumerating objects: 4278, done.
remote: Total 4278 (delta 0), reused 0 (delta 0), pack-reused 4278
Receiving objects: 100% (4278/4278), 54.86 MiB | 6.04 MiB/s, done.
Resolving deltas: 100% (1957/1957), done.
error: unable to create file S06-jetpack-room/CL04-AddDatabaseRoom /.gitignore: No such file or directory
fatal: cannot create directory at 'S06-jetpack-room/CL04-AddDatabaseRoom /.idea': No such file or directory
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by rikrdo000** [comment]
Mismo error agrego log de github

2020-11-15T20:36:14.511Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-11-15T20:36:33.219Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/Android-Avanzado/androidapp.git - rikrdo000 (has token)
2020-11-15T20:36:41.501Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/Android-Avanzado/androidapp.git C:\Users\jesus\Documents\GitHub\androidapp (took 8.242s)
2020-11-15T20:36:41.503Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/Android-Avanzado/androidapp.git C:\Users\jesus\Documents\GitHub\androidapp` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\jesus\Documents\GitHub\androidapp'...
remote: Enumerating objects: 4278, done.        
Receiving objects:   0% (1/4278)
Receiving objects:   1% (43/4278)
Receiving objects:   2% (86/4278)
Receiving objects:   3% (129/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:   4% (172/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:   5% (214/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:   6% (257/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:   7% (300/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:   8% (343/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:   9% (386/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  10% (428/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  11% (471/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  12% (514/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  13% (557/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  14% (599/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  15% (642/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  16% (685/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  17% (728/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  18% (771/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  19% (813/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  20% (856/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  21% (899/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  22% (942/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  23% (984/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  24% (1027/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  25% (1070/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  26% (1113/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  27% (1156/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  28% (1198/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  29% (1241/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  30% (1284/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  31% (1327/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  32% (1369/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  33% (1412/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  34% (1455/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  35% (1498/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  36% (1541/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  37% (1583/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  38% (1626/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  39% (1669/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  40% (1712/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  41% (1754/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  42% (1797/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  43% (1840/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  44% (1883/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  45% (1926/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  46% (1968/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  47% (2011/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  48% (2054/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  49% (2097/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  50% (2139/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  51% (2182/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  52% (2225/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  53% (2268/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  54% (2311/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  55% (2353/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  56% (2396/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  57% (2439/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  58% (2482/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  59% (2525/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  60% (2567/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  61% (2610/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  62% (2653/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  63% (2696/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  64% (2738/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  65% (2781/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  66% (2824/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  67% (2867/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  68% (2910/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  69% (2952/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  70% (2995/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  71% (3038/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  72% (3081/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  73% (3123/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  74% (3166/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  75% (3209/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  76% (3252/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  77% (3295/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  78% (3337/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  79% (3380/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  80% (3423/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  81% (3466/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  82% (3508/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  83% (3551/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  84% (3594/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  85% (3637/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  86% (3680/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  87% (3722/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  88% (3765/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  89% (3808/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  90% (3851/4278), 2.38 MiB | 4.62 MiB/s
Receiving objects:  90% (3855/4278), 8.92 MiB | 8.50 MiB/s
Receiving objects:  90% (3855/4278), 13.44 MiB | 6.38 MiB/s
Receiving objects:  90% (3855/4278), 20.52 MiB | 6.48 MiB/s
Receiving objects:  90% (3855/4278), 34.57 MiB | 8.08 MiB/s
Receiving objects:  90% (3855/4278), 37.32 MiB | 7.24 MiB/s
Receiving objects:  90% (3856/4278), 50.67 MiB | 8.54 MiB/s
Receiving objects:  91% (3893/4278), 50.67 MiB | 8.54 MiB/s
Receiving objects:  92% (3936/4278), 50.67 MiB | 8.54 MiB/s
Receiving objects:  93% (3979/4278), 50.67 MiB | 8.54 MiB/s
Receiving objects:  94% (4022/4278), 50.67 MiB | 8.54 MiB/s
Receiving objects:  95% (4065/4278), 50.67 MiB | 8.54 MiB/s
Receiving objects:  96% (4107/4278), 50.67 MiB | 8.54 MiB/s
Receiving objects:  97% (4150/4278), 50.67 MiB | 8.54 MiB/s
remote: Total 4278 (delta 0), reused 0 (delta 0), pack-reused 4278        
Receiving objects:  98% (4193/4278), 50.67 MiB | 8.54 MiB/s
Receiving objects:  99% (4236/4278), 50.67 MiB | 8.54 MiB/s
Receiving objects: 100% (4278/4278), 50.67 MiB | 8.54 MiB/s
Receiving objects: 100% (4278/4278), 54.86 MiB | 8.60 MiB/s, done.
Resolving deltas:   0% (0/1957)
Resolving deltas:   1% (22/1957)
Resolving deltas:   2% (42/1957)
Resolving deltas:   3% (67/1957)
Resolving deltas:   8% (169/1957)
Resolving deltas:  10% (212/1957)
Resolving deltas:  14% (286/1957)
Resolving deltas:  15% (313/1957)
Resolving deltas:  19% (380/1957)
Resolving deltas:  20% (392/1957)
Resolving deltas:  21% (411/1957)
Resolving deltas:  22% (440/1957)
Resolving deltas:  24% (470/1957)
Resolving deltas:  28% (557/1957)
Resolving deltas:  29% (568/1957)
Resolving deltas:  31% (609/1957)
Resolving deltas:  36% (705/1957)
Resolving deltas:  37% (729/1957)
Resolving deltas:  40% (791/1957)
Resolving deltas:  41% (807/1957)
Resolving deltas:  42% (829/1957)
Resolving deltas:  43% (849/1957)
Resolving deltas:  44% (866/1957)
Resolving deltas:  46% (914/1957)
Resolving deltas:  47% (927/1957)
Resolving deltas:  48% (940/1957)
Resolving deltas:  49% (959/1957)
Resolving deltas:  50% (985/1957)
Resolving deltas:  51% (999/1957)
Resolving deltas:  52% (1023/1957)
Resolving deltas:  53% (1043/1957)
Resolving deltas:  54% (1061/1957)
Resolving deltas:  55% (1077/1957)
Resolving deltas:  56% (1099/1957)
Resolving deltas:  57% (1116/1957)
Resolving deltas:  58% (1138/1957)
Resolving deltas:  59% (1157/1957)
Resolving deltas:  60% (1179/1957)
Resolving deltas:  61% (1204/1957)
Resolving deltas:  62% (1225/1957)
Resolving deltas:  63% (1237/1957)
Resolving deltas:  64% (1269/1957)
Resolving deltas:  67% (1320/1957)
Resolving deltas:  68% (1340/1957)
Resolving deltas:  69% (1353/1957)
Resolving deltas:  70% (1375/1957)
Resolving deltas:  71% (1396/1957)
Resolving deltas:  72% (1412/1957)
Resolving deltas:  73% (1431/1957)
Resolving deltas:  74% (1449/1957)
Resolving deltas:  75% (1469/1957)
Resolving deltas:  76% (1488/1957)
Resolving deltas:  77% (1507/1957)
Resolving deltas:  78% (1530/1957)
Resolving deltas:  79% (1552/1957)
Resolving deltas:  80% (1566/1957)
Resolving deltas:  81% (1587/1957)
Resolving deltas:  82% (1608/1957)
Resolving deltas:  83% (1626/1957)
Resolving deltas:  84% (1644/1957)
Resolving deltas:  85% (1664/1957)
Resolving deltas:  86% (1684/1957)
Resolving deltas:  87% (1703/1957)
Resolving deltas:  88% (1724/1957)
Resolving deltas:  89% (1743/1957)
Resolving deltas:  90% (1770/1957)
Resolving deltas:  91% (1782/1957)
Resolving deltas:  92% (1801/1957)
Resolving deltas:  93% (1824/1957)
Resolving deltas:  94% (1849/1957)
Resolving deltas:  95% (1874/1957)
Resolving deltas:  96% (1880/1957)
Resolving deltas:  97% (1901/1957)
Resolving deltas:  98% (1920/1957)
Resolving deltas: 100% (1957/1957)
Resolving deltas: 100% (1957/1957), done.
error: invalid path 'S06-jetpack-room/CL04-AddDatabaseRoom /.gitignore'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by alejandrocoding** [comment]
Hola a todos.

Acabo de clonar el repo sin problema aparente. Adjunto imagen:

<img width="721" alt="clone" src="https://user-images.githubusercontent.com/5755545/99462983-1a871d00-2935-11eb-8219-2849e080eddb.png">

Pueden ser errores derivados por otras razones, falta de espacio, cambios en el stash o algún fichero .git oculto...

Buscando por este error (Clone succeeded, but checkout failed) -> https://stackoverflow.com/questions/22041752/github-clone-succeeded-but-checkout-failed

Hay una respuesta bastante interesante y esto puede pasar a los usuarios de Windows sobre todo, y es que el path (o ruta) sea muy larga y Windows tiene limitación en cuanto al número máximo de caracteres en el path. Un usuario recomienda este comando: `git config --system core.longpaths true`

Personalmente recomiendo que en vez de ejecutar ese comando, crear una carpeta en el directorio raíz (en Windows, C:/prueba) acortando el path considerablemente, asegurarnos que la carpeta es nueva y está vacía, que tenemos espacio en el disco, y luego intentar de hacer el clone justo ahí.

De todas formas, esto no tiene nada que ver con el repositorio, he probado desde un MBP de 13, otro de 16 y un Windows 10, y en todos me descarga el repo sin problemas, el error reportado es ajeno al repo y aunque estoy encantado de contestar para ayudar, tengo que cerrar este issue al no ser algo de nuestra parte o del código/repositorio.
